# Task 2: print all available toppings

cakes = [
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'None'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Powdered Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Chocolate with Sprinkles'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Regular", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'None'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Powdered Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Chocolate with Sprinkles'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Chocolate", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'None'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Powdered Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Chocolate with Sprinkles'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Blueberry", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'None'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Powdered Sugar'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Chocolate with Sprinkles'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Cake', 'batter': "Devil's Food", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Raised', 'batter': "Regular", 'topping': 'None'},
    {'type': 'donut', 'name': 'Raised', 'batter': "Regular", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Raised', 'batter': "Regular", 'topping': 'Sugar'},
    {'type': 'donut', 'name': 'Raised', 'batter': "Regular", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Raised', 'batter': "Regular", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Regular", 'topping': 'None'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Regular", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Regular", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Regular", 'topping': 'Maple'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Chocolate", 'topping': 'None'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Chocolate", 'topping': 'Glazed'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Chocolate", 'topping': 'Chocolate'},
    {'type': 'donut', 'name': 'Old_Fashioned', 'batter': "Chocolate", 'topping': 'Maple'},
    {'type': 'bar', 'name': 'Bar', 'batter': "Regular", 'topping': 'Chocolate'},
    {'type': 'bar', 'name': 'Bar', 'batter': "Regular", 'topping': 'Maple'},
    {'type': 'twist', 'name': 'Twist', 'batter': "Regular", 'topping': 'Glazed'},
    {'type': 'twist', 'name': 'Twist', 'batter': "Regular", 'topping': 'Sugar'},
    {'type': 'filled', 'name': 'Filled', 'batter': "Regular", 'topping': 'Glazed'},
    {'type': 'filled', 'name': 'Filled', 'batter': "Regular", 'topping': 'Powdered Sugar'},
    {'type': 'filled', 'name': 'Filled', 'batter': "Regular", 'topping': 'Chocolate'},
    {'type': 'filled', 'name': 'Filled', 'batter': "Regular", 'topping': 'Maple'},
]
